version: '3.7'
networks:
    rede:
        name: rede
        driver: bridge

services:
    mongodb:
        container_name: mongodb
        image: mongo:3.6.18
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: 123
        ports:
            - "27017:27017"
        networks:
            - rede
