@host = http://localhost:8080/api/users

###

{{host}}

###

{{host}}/5f00d65dcd195f0665b9cddd


###

POST {{host}}
Content-Type: application/json

{
    "firstName": "02",
    "email": "2@email"
}

###

PUT {{host}}
Content-Type: application/json

{
    "id":"5f00ef5195ac016deade6fe3",
    "firstName": "00003",
    "email": "00003@email"
}

###

DELETE {{host}}/5f00ef5195ac016deade6fe3