@host = http://localhost:8080/api/users

###

{{host}}

###

{{host}}/id/5f00b5169a481147d04480611


###

POST {{host}}
Content-Type: application/json

{
    "firstName": "01",
    "email": "1@email"
}