
server:
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb://admin:123@127.0.0.1:27017
      database: test
  jpa:
    open-in-view: false
  output:
    ansi:
      enabled: always